# Generated by Django 3.2.18 on 2023-03-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XiangqiRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('white', models.CharField(default=None, max_length=255)),
                ('black', models.CharField(default=None, max_length=255)),
                ('turn', models.CharField(default='white', max_length=255)),
                ('board', models.CharField(default='rnbakabnr/ppppppppp/9/9/9/9/PPPPPPPPP/RNBAKABNR', max_length=255)),
                ('winner', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
