# Generated by Django 3.2.18 on 2023-03-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_xiangqiroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiangqiroom',
            name='black',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='xiangqiroom',
            name='white',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='xiangqiroom',
            name='winner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
