# Generated by Django 3.2.18 on 2023-03-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20230317_0529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
