# Generated by Django 3.2.18 on 2023-03-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiangqiroom',
            name='black_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xiangqiroom',
            name='white_ready',
            field=models.BooleanField(default=False),
        ),
    ]
