# Generated by Django 3.2.18 on 2023-04-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20230318_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiangqiroom',
            name='black_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xiangqiroom',
            name='white_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
