# Generated by Django 3.2.18 on 2023-04-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_black_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_white_ready',
            field=models.BooleanField(default=False),
        ),
    ]
