# Generated by Django 3.2.18 on 2023-04-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20230407_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XiangqiRoom',
        ),
    ]
