# Generated by Django 3.2.18 on 2023-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_delete_xiangqiroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_users',
            field=models.IntegerField(default=0),
        ),
    ]
