# Generated by Django 3.2.18 on 2023-04-30 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('volume_number', models.IntegerField(null=True)),
                ('volume', models.CharField(max_length=255, null=True)),
                ('chapter_number', models.IntegerField(null=True)),
                ('chapter', models.CharField(max_length=255, null=True)),
                ('section_number', models.IntegerField(null=True)),
                ('section', models.CharField(max_length=255, null=True)),
                ('game_number', models.IntegerField(null=True)),
                ('game', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
