# Generated by Django 3.2.18 on 2023-05-01 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xiangqibook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapter_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='game_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='volume_number',
        ),
        migrations.AddField(
            model_name='book',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='XiangqiBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
