# Generated by Django 3.2.18 on 2023-05-01 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xiangqibook', '0002_auto_20230501_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiangqibook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
