# Generated by Django 3.2.18 on 2023-04-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XiangqiGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GAMEID', models.CharField(max_length=100)),
                ('EVENT', models.CharField(max_length=255)),
                ('DATE', models.CharField(max_length=50)),
                ('ROUND', models.CharField(max_length=50)),
                ('RESULT', models.CharField(max_length=50)),
                ('REDPLAYER', models.CharField(max_length=255)),
                ('REDCLUB', models.CharField(max_length=255)),
                ('BLACKPLAYER', models.CharField(max_length=255)),
                ('BLACKCLUB', models.CharField(max_length=255)),
                ('OPENING', models.CharField(max_length=255)),
                ('VARIATION', models.CharField(max_length=255)),
            ],
        ),
    ]
