# Generated by Django 3.2.18 on 2023-04-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote', '0002_xiangqigame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiangqigame',
            name='DATE',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='xiangqigame',
            name='GAMEID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='xiangqigame',
            name='RESULT',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='xiangqigame',
            name='ROUND',
            field=models.CharField(max_length=255),
        ),
    ]
