# Generated by Django 3.2.18 on 2023-04-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote', '0004_auto_20230402_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='XiangqiMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GAMEID', models.CharField(max_length=255)),
                ('GAME', models.TextField(null=True)),
                ('RESULT', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
