# Generated by Django 3.2.18 on 2023-04-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote', '0005_xiangqimove'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XiangqiMove',
        ),
        migrations.AddField(
            model_name='xiangqigame',
            name='GAME',
            field=models.TextField(null=True),
        ),
    ]
