# Generated by Django 3.2.18 on 2023-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xnote', '0006_auto_20230402_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBookPlayedByMasters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('fen', models.TextField()),
                ('move', models.CharField(max_length=5)),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
    ]
